### ISSUE TITLE
LumiCalReco: Link clusters with calorimeter hits

### ISSUE THREAD

**Issue by andresailer** [FCALSW/FCalClusterer#8]
Created clusters should be linked with calorimeter hits that make up the cluster

**Comment by pawlikb** [comment]
You are perfectly right.  There is even a comment in MarlinLumiCalClusterer I left some time ago.
But solution, I was thinking about, was ugly and time consuming in the situation we had. Now in DD4 era it is even worst because we do not have original cellID's. I am considering how/where to store hit reference in original hit collection....

**Comment by andresailer** [comment]
we make a vector linking new cellID to original hit(pointer) or link the new hit to the original hit
